In [36]:
import numpy as np

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.full(10, 666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [41]:
np.full((2, 3), 333)

array([[333, 333, 333],
       [333, 333, 333]])

In [42]:
np.arange(2,10,2)

array([2, 4, 6, 8])